/* =============================================================================================
 * Damiano Tasso 944232
 * 
 * In this .h file there is the definition of the interrupt generated by the BUTTON at its press
 * =============================================================================================
*/
#ifndef __SERVICE_ROUTINES_H__
    #define __SERVICE_ROUTINES_H__
    
    #include "global.h"
    #include "I2C_protocol.h"
    
    CY_ISR_PROTO(custom_isr_BUTTON);
    
 #endif
/* [] END OF FILE */